### PR TITLE
Typeoverride merge fix

### LINKED ISSUE #153: Thanos store uses ephemeral storage and fills up the Node storage.
**Describe the bug**
Thanos operator is used for deploying the the thanos components (storegateway, query, query frontend).

Thanos store container fills up the ephemeral disk that is only 50GB.

Tried configuring the PVC for the store container, but the operator is not accepting the additional PVC volume and gives the below error.

thanos> Reconciler error failed to reconcile resource: failed to create resource: creating resource failed: Deployment.apps "sandbox-us-west-2-thanos-cluster-store" is invalid: spec.template.spec.volumes[0].persistentVolumeClaim: Forbidden: may not specify more than 1 volume type (name: sandbox-us-west-2-thanos-cluster-store, namespace: monitoring, apiVersion: apps/v1, kind: Deployment, name: sandbox-us-west-2-thanos-cluster-store, namespace: monitoring, apiVersion: apps/v1, kind: Deployment) name: sandbox-us-west-2, namespace: monitoring

Here is my Thanos store gateway config input given to Thanos CR.

storeGateway:
indexCacheSize: 250MB
deploymentOverrides:
spec:
template:
spec:
containers:
- image:thanos/thanos:v0.19.0-rc.0
imagePullPolicy: Always
name: store
volumeMounts:
- mountPath: /data
name: task-pv-storage
volumes:
- name: task-pv-storage
persistentVolumeClaim:
claimName: clusterstore-pvc

This issue is not happening in other clusters where the ephemeral disk is 100GB. I tried configuring the IndexCacheSize to 10GB, and it is still not taking effect.

Have anyone encountered this issue?

How do we configure the Thanos store Gateway to use the PVC or configure the object download limit on the ephemeral disk?

Thanos Operator details:

Thanos Version: thanos:v0.19.0-rc.0

Thanos Operator Version: 0.3.3

Object Storage Provider: S3

### PR DESCRIPTION
**Pull request by pepov**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #153 
| License         | Apache 2.0

### What's in this PR?
Upgrade to operator-tools where the typeoverride merge fix using reflect to create a new object instead of the original one is available

### Why?
This replaces #154 and avoids intrusive changes in the existing codebase.

### CODE REVIEW

**Review by siliconbrain — APPROVED** [review]
lgtm

**Comment by dpachiappan** [comment]
Hi @pepov ,

Thanks for fixing it. I pulled in the changes from the type override fix, but I still get the same error.

thanos> Reconciler error failed to reconcile resource: failed to create resource: creating resource failed: Deployment.apps "thanos-thanos-store" is invalid: [spec.template.spec.volumes[0].persistentVolumeClaim: Forbidden: may not specify more than 1 volume type, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "store-vol"] (name: thanos-thanos-store, namespace: monitoring, apiVersion: apps/v1, kind: Deployment, name: thanos-thanos-store, namespace: monitoring, apiVersion: apps/v1, kind: Deployment) name: thanos, namespace: monitoring


Changes:

I pulled in only the CRDs and applied it as I don't think anything else is changes as part of your fix. Let me know if it is wrong.


Here is my thanos spec for the storegateway:

apiVersion: monitoring.banzaicloud.io/v1alpha1
kind: Thanos
metadata:
  annotations:
    objectset.rio.cattle.io/id: default-sbx-sfo-mon-thingspace-thanos-cluster
  labels:
    app.kubernetes.io/instance: thanos-cluster
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: thanos
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: thanos-cluster-0.1.0
    objectset.rio.cattle.io/hash: ef8f7dd5fede88fdf3285d05cdc7db81fdf8c60f
  name: thanos
spec:
  enableRecreateWorkloadOnImmutableFieldChange: true
  query:
    deploymentOverrides:
      spec:
        template:
          spec:
            containers:
            - image: 349211140923.dkr.ecr.us-east-1.amazonaws.com/thanos/thanos:v0.19.0-rc.0
              imagePullPolicy: Always
              name: query
    queryReplicaLabel:
    - prometheus_replica
  queryFrontend:
    HTTPIngress:
      certificate: query-monitoring-tls
      host: query-monitoring-sandbox.internal-us-west-2.tscloudservice.com
      path: /
    deploymentOverrides:
      spec:
        template:
          spec:
            containers:
            - image: 349211140923.dkr.ecr.us-east-1.amazonaws.com/thanos/thanos:v0.19.0-rc.0
              imagePullPolicy: Always
              name: query-frontend
    metaOverrides:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: ingress-internal
        kubernetes.io/tls-acme: "true"
  rule:
    statefulsetOverrides:
      spec:
        template:
          spec:
            containers:
            - image: 349211140923.dkr.ecr.us-east-1.amazonaws.com/thanos/thanos:v0.19.0-rc.0
              imagePullPolicy: Always
              name: rule
  storeGateway:
    deploymentOverrides:
      spec:
        template:
          spec:
            containers:
            - image: 349211140923.dkr.ecr.us-east-1.amazonaws.com/thanos/thanos:v0.19.0-rc.0
              imagePullPolicy: Always
              name: store
              volumeMounts:
              - mountPath: /data
                name: store-vol
            volumes:
            - name: store-vol
              persistentVolumeClaim:
                claimName: clusterstore-pvc
    storeEnableIndexHeaderLazyReader: true

**Comment by dpachiappan** [comment]
> Hi @pepov ,
> 
> Thanks for fixing it. I pulled in the changes from the type override fix, but I still get the same error.
> 
> thanos> Reconciler error failed to reconcile resource: failed to create resource: creating resource failed: Deployment.apps "thanos-thanos-store" is invalid: [spec.template.spec.volumes[0].persistentVolumeClaim: Forbidden: may not specify more than 1 volume type, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "store-vol"] (name: thanos-thanos-store, namespace: monitoring, apiVersion: apps/v1, kind: Deployment, name: thanos-thanos-store, namespace: monitoring, apiVersion: apps/v1, kind: Deployment) name: thanos, namespace: monitoring
> 
> Changes:
> 
> I pulled in only the CRDs and applied it as I don't think anything else is changes as part of your fix. Let me know if it is wrong.
> 
> Here is my thanos spec for the storegateway:
> 
> apiVersion: monitoring.banzaicloud.io/v1alpha1 kind: Thanos metadata: annotations: objectset.rio.cattle.io/id: default-sbx-sfo-mon-thingspace-thanos-cluster labels: app.kubernetes.io/instance: thanos-cluster app.kubernetes.io/managed-by: Helm app.kubernetes.io/name: thanos app.kubernetes.io/version: 1.16.0 helm.sh/chart: thanos-cluster-0.1.0 objectset.rio.cattle.io/hash: ef8f7dd5fede88fdf3285d05cdc7db81fdf8c60f name: thanos spec: enableRecreateWorkloadOnImmutableFieldChange: true query: deploymentOverrides: spec: template: spec: containers: - image: <<>> imagePullPolicy: Always name: query queryReplicaLabel: - prometheus_replica queryFrontend: HTTPIngress: certificate: query-monitoring-tls host: query-monitoring-sandbox.internal-us-west-2.tscloudservice.com path: / deploymentOverrides: spec: template: spec: containers: - image: <<>> imagePullPolicy: Always name: query-frontend metaOverrides: annotations: cert-manager.io/cluster-issuer: letsencrypt-prod kubernetes.io/ingress.class: ingress-internal kubernetes.io/tls-acme: "true" rule: statefulsetOverrides: spec: template: spec: containers: - image: <<>> imagePullPolicy: Always name: rule storeGateway: deploymentOverrides: spec: template: spec: containers: - image: <<>> imagePullPolicy: Always name: store volumeMounts: - mountPath: /data name: store-vol volumes: - name: store-vol persistentVolumeClaim: claimName: clusterstore-pvc storeEnableIndexHeaderLazyReader: true

@pepov

**Comment by pepov** [comment]
@dpachiappan you need to use the latest image which is `ghcr.io/banzaicloud/thanos-operator:0.3.4`

**Comment by dpachiappan** [comment]
Thanks @pepov  for your continued help.  I updated the operator to the latest image ghcr.io/banzaicloud/thanos-operator:0.3.4. Now the operator is failing to create the receiver with the error related to object modified. I presented the error at the end of this message.

If I comment out the receiver, then the store gateway comes up properly with the attached PVC. However, if I enable the receiver,  store POD gets deleted by the operator and the operator stuck in the loop to reconcile the receiver resource. This behavior is not happening with the previous thanos version 0.3.3.


Here is the error from the operator regarding the receiver reconciliation.


{"level":"error","ts":"2021-10-05T18:24:45.027Z","logger":"controller-runtime.manager.controller.receiver","msg":"Reconciler error","reconciler group":"monitoring.banzaicloud.io","reconciler kind":"Receiver","name":"thanos","namespace":"monitoring","error":"failed to reconcile resource: updating resource failed: Operation cannot be fulfilled on statefulsets.apps \"thanos-receiver-thanos\": the object has been modified; please apply your changes to the latest version and try again","errorVerbose":"Operation cannot be fulfilled on statefulsets.apps \"thanos-receiver-thanos\": the object has been modified; please apply your changes to the latest version and try again\nupdating resource failed\ngithub.com/banzaicloud/operator-tools/pkg/reconciler.(*GenericResourceReconciler).ReconcileResource\n\t/go/pkg/mod/github.com/banzaicloud/operator-tools@v0.25.2/pkg/reconciler/resource.go:445\ngithub.com/banzaicloud/thanos-operator/pkg/resources.Dispatch\n\t/workspace/pkg/resources/types.go:54\ngithub.com/banzaicloud/thanos-operator/pkg/resources.(*ReceiverReconciler).ReconcileResources\n\t/workspace/pkg/resources/receiver.go:89\ngithub.com/banzaicloud/thanos-operator/pkg/resources/receiver.(*Receiver).Reconcile\n\t/workspace/pkg/resources/receiver/receiver.go:117\ngithub.com/banzaicloud/thanos-operator/pkg/resources.RunReconcilers\n\t/workspace/pkg/resources/componentreconciler.go:25\ngithub.com/banzaicloud/thanos-operator/controllers.(*ReceiverReconciler).Reconcile\n\t/workspace/controllers/receiver_controller.go:65\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nfailed to reconcile resource","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214"}









ghcr.io/banzaicloud/thanos-operator:0.3.4

**Comment by dpachiappan** [comment]
Thanks a lot @pepov . It worked like a charm! Appreciate all your help.

**Pull request merged**
